'use client';

import { useState } from 'react';

import SamplePaperCard from '../SamplePapers/SamplePaperCard';
import { samplePapers } from '../SamplePapers/samplePapersData';
import { SectionEyebrow, SectionTitle } from './SectionPrimitives';

const SamplePapersSection = () => {
  const [selectedPaper, setSelectedPaper] = useState(null);
  const featuredPapers = samplePapers.slice(0, 3);

  return (
    <section id="sample-papers" className="scroll-mt-28 border-y border-[#12213a] bg-[#0e1a32]">
      <div className="mx-auto w-full max-w-6xl px-5 py-16 sm:px-6">
        <SectionEyebrow>SAMPLE PAPERS</SectionEyebrow>
        <div className="mt-4">
          <SectionTitle className="max-w-none lg:whitespace-nowrap">
            Examples That Showcase Academic Output
          </SectionTitle>
        </div>
        <p className="mt-5 max-w-3xl text-sm leading-7 text-slate-300 sm:text-base">
          Explore high-quality assignments and solutions generated by Vidya AI across various
          technical subjects.
        </p>
        <div className="mt-10 grid gap-5 lg:grid-cols-3">
          {featuredPapers.map((paper) => (
            <SamplePaperCard
              key={paper.id}
              paper={paper}
              expanded={selectedPaper === paper.id}
              onToggle={() => setSelectedPaper(selectedPaper === paper.id ? null : paper.id)}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default SamplePapersSection;
