'use client'

import { useState } from 'react'
import { ArrowRight, FileText, Filter, Search, Sparkles } from 'lucide-react'

import { primaryButtonClass } from '@/components/Landing/buttonClasses'
import SamplePaperCard from '@/components/SamplePapers/SamplePaperCard'
import { difficulties, samplePapers, subjects } from '@/components/SamplePapers/samplePapersData'

export default function SamplePapersPage() {
  const [selectedSubject, setSelectedSubject] = useState('All Subjects')
  const [selectedDifficulty, setSelectedDifficulty] = useState('All Levels')
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedPaper, setSelectedPaper] = useState<string | null>(null)

  const filteredPapers = samplePapers.filter(paper => {
    const matchesSubject = selectedSubject === 'All Subjects' || paper.subject === selectedSubject
    const matchesDifficulty = selectedDifficulty === 'All Levels' || paper.difficulty === selectedDifficulty
    const matchesSearch = searchQuery === '' ||
      paper.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      paper.subject.toLowerCase().includes(searchQuery.toLowerCase()) ||
      paper.topics.some(topic => topic.toLowerCase().includes(searchQuery.toLowerCase()))

    return matchesSubject && matchesDifficulty && matchesSearch
  })

  return (
    <div className="mx-auto w-full max-w-7xl px-5 py-12 sm:px-6">
      {/* Header */}
      <div className="relative overflow-hidden rounded-[32px] border border-[#182842] bg-[radial-gradient(circle_at_top,rgba(67,234,214,0.12),transparent_50%),linear-gradient(180deg,rgba(255,255,255,0.04),rgba(255,255,255,0.02))] px-6 py-7 text-center shadow-[0_24px_80px_rgba(0,0,0,0.18)] sm:px-10 sm:py-8">
        <div className="pointer-events-none absolute left-0 top-0 h-full w-24 bg-[radial-gradient(circle_at_left,rgba(67,234,214,0.08),transparent_72%)]" />
        <div className="inline-flex items-center gap-2 rounded-full border border-[#43ead6]/18 bg-[#43ead6]/10 px-4 py-2 text-sm font-medium text-[#43ead6]">
          <Sparkles className="h-4 w-4" />
          AI-Generated Assignments
        </div>
        <h1 className="mt-4 text-3xl font-semibold tracking-tight text-white sm:text-4xl">
          Sample Papers
        </h1>
        <p className="mx-auto mt-3 max-w-3xl text-sm leading-7 text-slate-300 sm:text-base">
          Explore high-quality assignments and solutions generated by Vidya AI across various technical subjects.
          See the quality and depth of our AI-generated content.
        </p>
      </div>

      {/* Filters and Search */}
      <div className="mt-6 rounded-[28px] border border-[#182842] bg-[#0d1a33] p-5 shadow-[0_18px_50px_rgba(0,0,0,0.18)]">
        <div className="flex flex-col md:flex-row gap-4">
          {/* Search */}
          <div className="flex-1">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-500" />
              <input
                type="text"
                placeholder="Search papers, topics..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full rounded-[18px] border border-[#223556] bg-[#08172d] py-3 pl-10 pr-4 text-white placeholder:text-slate-500 focus:outline-none focus:ring-2 focus:ring-[#43ead6]/40 focus:border-[#43ead6]/30"
              />
            </div>
          </div>

          {/* Subject Filter */}
          <div className="flex items-center gap-2">
            <Filter className="h-5 w-5 text-slate-500" />
            <select
              value={selectedSubject}
              onChange={(e) => setSelectedSubject(e.target.value)}
              className="rounded-[18px] border border-[#223556] bg-[#08172d] px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-[#43ead6]/40 focus:border-[#43ead6]/30"
            >
              {subjects.map(subject => (
                <option key={subject} value={subject}>{subject}</option>
              ))}
            </select>
          </div>

          {/* Difficulty Filter */}
          <div>
            <select
              value={selectedDifficulty}
              onChange={(e) => setSelectedDifficulty(e.target.value)}
              className="rounded-[18px] border border-[#223556] bg-[#08172d] px-4 py-3 text-white focus:outline-none focus:ring-2 focus:ring-[#43ead6]/40 focus:border-[#43ead6]/30"
            >
              {difficulties.map(difficulty => (
                <option key={difficulty} value={difficulty}>{difficulty}</option>
              ))}
            </select>
          </div>
        </div>

        {/* Active Filters */}
        {(selectedSubject !== 'All Subjects' || selectedDifficulty !== 'All Levels' || searchQuery) && (
          <div className="mt-4 flex flex-wrap items-center gap-2">
            <span className="text-sm text-slate-400">Active filters:</span>
            {selectedSubject !== 'All Subjects' && (
              <span className="flex items-center gap-1 rounded-full border border-[#43ead6]/18 bg-[#43ead6]/10 px-3 py-1 text-sm text-[#43ead6]">
                {selectedSubject}
                <button onClick={() => setSelectedSubject('All Subjects')} className="hover:text-white">×</button>
              </span>
            )}
            {selectedDifficulty !== 'All Levels' && (
              <span className="flex items-center gap-1 rounded-full border border-[#4bc2ff]/18 bg-[#4bc2ff]/10 px-3 py-1 text-sm text-[#7ed4ff]">
                {selectedDifficulty}
                <button onClick={() => setSelectedDifficulty('All Levels')} className="hover:text-white">×</button>
              </span>
            )}
            {searchQuery && (
              <span className="flex items-center gap-1 rounded-full border border-white/12 bg-white/5 px-3 py-1 text-sm text-slate-200">
                "{searchQuery}"
                <button onClick={() => setSearchQuery('')} className="hover:text-white">×</button>
              </span>
            )}
          </div>
        )}
      </div>

      {/* Results Count */}
      <div className="mb-5 mt-5">
        <p className="text-slate-400">
          Showing <span className="font-semibold text-white">{filteredPapers.length}</span> {filteredPapers.length === 1 ? 'paper' : 'papers'}
        </p>
      </div>

      {/* Papers Grid */}
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
        {filteredPapers.map((paper) => (
          <SamplePaperCard
            key={paper.id}
            paper={paper}
            expanded={selectedPaper === paper.id}
            onToggle={() => setSelectedPaper(selectedPaper === paper.id ? null : paper.id)}
          />
        ))}
      </div>

      {/* No Results */}
      {filteredPapers.length === 0 && (
        <div className="rounded-[28px] border border-[#182842] bg-[#0d1a33] py-12 text-center">
          <FileText className="mx-auto mb-4 h-16 w-16 text-slate-500" />
          <h3 className="mb-2 text-xl font-semibold text-white">No papers found</h3>
          <p className="mb-4 text-slate-400">Try adjusting your filters or search query</p>
          <button
            onClick={() => {
              setSelectedSubject('All Subjects')
              setSelectedDifficulty('All Levels')
              setSearchQuery('')
            }}
            className="rounded-full bg-[#43ead6] px-6 py-2 text-sm font-medium text-[#051224] transition hover:bg-[#43ead6]/90"
          >
            Clear All Filters
          </button>
        </div>
      )}

      {/* CTA Section */}
      <div className="mt-16 rounded-[32px] border border-[#182842] bg-[radial-gradient(circle_at_top,rgba(67,234,214,0.12),transparent_55%),linear-gradient(180deg,rgba(255,255,255,0.04),rgba(255,255,255,0.02))] p-8 text-center shadow-[0_24px_80px_rgba(0,0,0,0.22)] sm:p-12">
        <Sparkles className="mx-auto mb-4 h-12 w-12 text-[#43ead6]" />
        <h2 className="mb-4 text-3xl font-semibold tracking-tight text-white">
          Generate Your Own Assignments
        </h2>
        <p className="mx-auto mb-6 max-w-2xl text-slate-300">
          These are just examples! With Vidya AI, you can generate unlimited high-quality assignments
          across any subject, tailored to your course materials and learning objectives.
        </p>
        <a
          href="/login"
          className={primaryButtonClass}
        >
          Get Started Free
          <ArrowRight className="h-4 w-4" />
        </a>
      </div>
    </div>
  )
}
